export const _LANGAUGE_MAP_UI = new Map([
  [
    "(except on cover and section slides)",
    "(sauf sur les diapositives de couverture et de section)",
  ],
  ["add", "ajouter"],
  ["Add", "Ajouter"],
  ["Add assets", "Ajouter des ressources"],
  ["Add col", "Ajouter une colonne"],
  ["Add immediately after this", "Ajouter à la suite"],
  ["Add logo", "Ajouter un logo"],
  ["Add more", "Ajouter plus"],
  [
    "Add multiple emails, separated by a comma, semicolon, or line break.",
    "Ajouter plusieurs e-mails (séparés par virgule, point-virgule ou saut de ligne)",
  ],
  ["Add new user", "Ajouter un utilisateur"],
  ["Add row", "Ajouter une ligne"],
  ["Add to end", "Ajouter à la fin"],
  ["Add users", "Ajouter des utilisateurs"],
  ["Add watermark", "Ajouter un filigrane"],
  ["admin", "admin"],
  ["Admin", "Admin"],
  ["Admin area 2", "Unité administrative 2"],
  ["Admin area 3", "Unité administrative 3"],
  ["Admin area 4", "Unité administrative 4"],
  ["Admin areas", "Unité administrative"],
  ["admin areas", "unité administrative"],
  ["ADMIN AREAS", "UNITÉ ADMINISTRATIVE"],
  [
    "Aggregated data for the visualization",
    "Données agrégées pour la visualisation",
  ],
  ["All admin areas", "Toutes les unités administratives"],
  ["All indicators", "Tous les indicateurs"],
  ["Allow individual row limits", "Autoriser des limites par ligne"],
  [
    "Allow visualization to shrink or stretch",
    "Autoriser la visualisation à s’étirer ou se réduire",
  ],
  ["anc1", "cpn1"],
  ["anc4", "cpn4"],
  ["Antenatal care 1", "Consultation prénatale 1"],
  ["Antenatal care 4", "Consultation prénatale 4"],
  [
    "Are you sure you want to delete this",
    "Êtes-vous sûr de vouloir supprimer ceci ?",
  ],
  [
    "Are you sure you want to delete this visualization?",
    "Êtes-vous sûr de vouloir supprimer cette visualisation ?",
  ],
  ["Areas", "Zones"],
  ["Ascending", "Croissant"],
  ["Assets", "Ressources"],
  ["Background", "Arrière-plan"],
  ["Background detail", "Détail de l'arrière-plan"],
  ["Backup", "Sauvegarde"],
  ["Bar chart", "Graphique à barres"],
  ["Bars", "Barres"],
  ["BCG vaccine", "Vaccination BCG"],
  ["Bottom", "Bas"],
  ["Can edit this project", "Peut modifier ce projet"],
  ["Can view this project", "Peut consulter ce projet"],
  ["Cancel", "Annuler"],
  ["Caption", "Titre"],
  ["Change", "Modifier"],
  ["Check again", "Vérifier à nouveau"],
  ["Checking import...", "Vérification de l’importation..."],
  ["Clear", "Effacer"],
  ["Col span", "Étendue de colonnes"],
  ["Color scale", "Échelle de couleurs"],
  ["Color scale mapping", "Correspondance de l’échelle de couleurs"],
  ["Column groups", "Groupes de colonnes"],
  ["Columns", "Colonnes"],
  ["Common structure", "Structure commune"],
  ["Conditional formatting", "Mise en forme conditionnelle"],
  ["Connecting to project", "Connexion au projet"],
  ["Connection failed", "Échec de la connexion"],
  ["Content", "Contenu"],
  ["Content type", "Type de contenu"],
  ["Continue", "Continuer"],
  ["Cover", "Couverture"],
  ["Cover whole area", "Couvrir toute la zone"],
  ["Coverage data", "Données de couverture"],
  ["Create new visualization", "Créer une nouvelle visualisation"],
  ["Create project", "Créer un projet"],
  ["Create report", "Créer un rapport"],
  ["Create visualization", "Créer une visualisation"],
  ["Custom", "Personnalisé"],
  ["Custom colours", "Couleurs personnalisées"],
  ["Data", "Données"],
  ["DATA SOURCE", "SOURCE DE DONNÉES"],
  ["Data sources", "Sources de données"],
  ["Data values", "Valeurs des données"],
  ["Date imported", "Date d’importation"],
  ["Date text", "Texte de date"],
  ["Decimal places", "Décimales"],
  ["Default", "Par défaut"],
  ["Del row", "Supprimer la ligne"],
  ["Delete", "Supprimer"],
  ["delete", "supprimer"],
  ["Delete project", "Supprimer le projet"],
  ["Delete report", "Supprimer le rapport"],
  ["Delete selected col", "Supprimer la colonne sélectionnée"],
  ["Delete this import", "Supprimer cette importation"],
  ["delivery", "accouchements"],
  ["Descending", "Décroissant"],
  ["Diff areas", "Zones de différences"],
  ["Different charts (replicants)", "Graphiques multiples (réplicants)"],
  ["Disable", "Désactiver"],
  ["Disaggregate", "Désagréger"],
  ["Disaggregate by", "Désagréger par"],
  ["Discard import", "Annuler l’importation"],
  ["Discard upload", "Annuler le téléversement"],
  ["Display format", "Format d'affichage"],
  ["Done", "Terminé"],
  ["Download", "Télécharger"],
  [
    "Drag the slides on the left to reorder",
    "Glisser-déposer les diapositives à gauche pour les réorganiser",
  ],
  ["Duplicate", "Dupliquer"],
  ["Duplicate report", "Dupliquer le rapport"],
  ["Duplicate visualization", "Dupliquer la visualisation"],
  ["Edit", "Modifier"],
  ["Edit name", "Modifier le nom"],
  ["Edit project name", "Modifier le nom du projet"],
  ["Edit visualization name", "Modifier le nom de la visualisation"],
  ["Editor", "Éditeur"],
  ["Email", "E-mail"],
  ["Enable", "Activer"],
  ["Existing csv file to use", "Fichier CSV existant à utiliser"],
  ["FACILITIES", "ÉTABLISSEMENTS DE SANTÉ"],
  [
    "Fetching data to be visualized...",
    "Récupération des données à visualiser...",
  ],
  ["Fetching data...", "Récupération des données..."],
  ["Fetching data...", "Récupération des données..."],
  ["figure", "figure"],
  ["Figure", "Figure"],
  ["Filter", "Filtre"],
  ["Filter time period", "Filtrer par période"],
  ["FILTERED", "FILTRÉ"],
  ["First month", "Premier mois"],
  ["Fit inside area", "Adapter à l'intérieur de la zone"],
  ["Fit-within", "Adapter à l’espace disponible"],
  ["Footer logos", "Logos de pied de page"],
  ["Footer text", "Texte de pied de page"],
  ["Footnote", "Note de bas de page"],
  ["Force y-axis max of 100%", "Forcer le maximum de l’axe Y à 100 %"],
  ["Format", "Format"],
  ["Freeform", "Libre"],
  ["General", "Général"],
  ["Getting module details...", "Récupération des informations du module…"],
  ["Go to new report", "Accéder au nouveau rapport"],
  ["Grid", "Grille"],
  ["Has data", "Contient des données"],
  ["Header / footer", "En-tête / pied de page"],
  ["Header logos", "Logos d’en-tête"],
  ["Header text", "Texte d’en-tête"],
  ["Health facilities", "Établissements de santé"],
  ["health facilities", "établissements de santé"],
  ["Health facility data", "Données sur les établissements de santé"],
  ["Hide legend", "Masquer la légende"],
  ["Hide placeholder shading", "Masquer l'ombrage de l'espace réservé"],
  ["Hide visualization caption", "Masquer le titre de la visualisation"],
  [
    "Hide visualization footnote",
    "Masquer la note de bas de page de visualisation",
  ],
  [
    "Hide visualization sub-caption",
    "Masquer le sous-titre de la visualisation",
  ],
  ["HMIS data", "Données HMIS"],
  ["Image", "Image"],
  ["Image file", "Fichier image"],
  ["Image fit", "Ajuster l'image"],
  ["IMPORT IN PROGRESS", "IMPORTATION EN COURS"],
  ["Import information", "Informations sur l’importation"],
  ["Imports", "Importations"],
  ["Imports in progress", "Importations en cours"],
  [
    "In order to disable this module you must first disable the modules that depend on it, including",
    "Pour désactiver ce module, les modules qui en dépendent doivent d’abord être désactivés, y compris :",
  ],
  ["Include all admin areas", "Inclure tous les unités administratives"],
  ["Include all indicators", "Inclure tous les indicateurs"],
  ["Include National results", "Inclure les résultats nationaux"],
  ["Indicator", "Indicateur"],
  ["Indicators", "Indicateurs"],
  ["indicators", "indicateurs"],
  ["INDICATORS", "INDICATEURS"],
  ["Inpatient visit", "Hospitalisation"],
  ["Instance admin", "Administrateur de l’instance"],
  ["Instance permissions", "Droits d’accès à l’instance"],
  ["Institutional delivery", "Accouchement institutionnel"],
  ["Last month", "Mois précédent"],
  ["Last run", "Dernière exécution"],
  ["Last updated", "Dernière mise à jour"],
  ["Latest import", "Dernière importation"],
  ["Lines", "Lignes"],
  ["Loading", "Chargement"],
  ["Loading asset files...", "Chargement des fichiers ressources..."],
  ["Loading files...", "Chargement des fichiers..."],
  ["Loading import info...", "Chargement des informations d’importation..."],
  ["Loading instance info...", "Chargement des informations de l’instance..."],
  ["Loading project details...", "Récupération des informations du projet…"],
  ["Loading report item...", "Chargement de l’élément du rapport..."],
  ["Loading report...", "Chargement du rapport..."],
  ["Loading visualization...", "Chargement de la visualisation..."],
  ["Loading...", "Chargement..."],
  ["Login details", "Identifiants"],
  ["Logos", "Logos"],
  ["Logos to use", "Logos à utiliser"],
  ["Logs", "Journaux  des données"],
  ["Main section text", "Texte de la section principale"],
  ["Main title text", "Texte du titre principal"],
  ["Make admin", "Attribuer le rôle d’administrateur"],
  ["Make non-admin", "Retirer le rôle d’administrateur"],
  [
    "Make this visualization a default visualization",
    "Définir cette visualisation comme visualisation par défaut",
  ],
  ["Margin", "Marge"],
  ["Max admin area", "Zone administrative maximale"],
  ["Max-width", "Largeur maximale"],
  ["Measles vaccine 1", "Vaccination Rougeole 1"],
  ["Measles vaccine 2", "Vaccination Rougeole 2"],
  ["Module", "Module"],
  ["Modules", "Modules"],
  ["Monthly", "Mensuel"],
  ["Move col", "Déplacer la colonne"],
  ["National", "National"],
  ["Needs selection", "Nécessite une sélection"],
  [
    "New family planning acceptors",
    "Nouveaux utilisateurs de la planification familiale",
  ],
  ["New rows added", "Nouvelles lignes ajoutées"],
  ["New visualization name", "Nom de la nouvelle visualisation"],
  ["Next", "Suivant"],
  ["No", "Non"],
  ["No conflicts!", "Aucun conflit !"],
  ["No data added", "Aucune donnée ajoutée"],
  [
    "No logos set in report settings",
    "Aucun logo défini dans les paramètres du rapport",
  ],
  ["No margins", "Sans marges"],
  ["No matching reports", "Aucun rapport correspondant"],
  ["No matching visualizations", "Aucune visualisation correspondante"],
  ["No permissions for this project", "Aucun droit d'accès à ce projet"],
  ["No reports", "Aucun rapport"],
  ["No slides", "Aucune diapositive"],
  ["No visualizations", "Aucune visualisation"],
  ["None", "Aucun(e)"],
  [
    "Number of facility records",
    "Nombre d’enregistrements d’établissements de santé",
  ],
  ["Number of records", "Nombre d'enregistrements"],
  ["Old rows unchanged", "Lignes précédentes non modifiées"],
  ["Old rows updated", "Lignes précédentes modifiées"],
  ["opd", "consultations"],
  ["Outpatient visit", "Visite ambulatoire"],
  ["page", "page"],
  ["pages", "pages"],
  ["Pending", "En attente"],
  ["Penta 1 vaccine", "Vaccination Penta 1"],
  ["Penta 3 vaccine", "Vaccination Penta 3"],
  ["Period", "Période"],
  ["Placeholder", "Espace réservé"],
  ["Policy brief", "Note politique"],
  ["Population data", "Données démographiques"],
  ["Posnatal care 1 (mothers)", "Consultation postnatale 1 (mères)"],
  ["Postnatal care 1 (newborns)", "Consultation postnatale 1 (nouveaux-nés)"],
  ["Present as", "Afficher sous forme de"],
  ["Presentation", "Présentation"],
  ["Presentation type", "Type de présentation"],
  ["Presenters text", "Texte du présentateur"],
  ["Prev", "Retour"],
  ["Previous imports", "Importations précédentes"],
  ["PROJECT", "PROJET"],
  ["Project name", "Nom du projet"],
  ["Project users", "Utilisateurs du projet"],
  ["Projects", "Projets"],
  ["Quarterly", "Trimestriel"],
  ["Re-run", "Relancer"],
  ["Remove this user", "Supprimer cet utilisateur"],
  ["Reorder", "Réordonner"],
  ["Reorder pages", "Réordonner"],
  ["Reorder slides", "Réordonner"],
  ["REPL. & FILT.", "REMPL. & FILT."],
  ["Replicant", "Réplicant"],
  ["REPLICATED", "RÉPLIQUÉ"],
  ["REPORT", "RAPPORT"],
  ["Report color theme", "Thème de couleur du rapport"],
  ["Report name", "Nom du rapport"],
  ["Report settings", "Configuration du rapport"],
  ["Reports", "Rapports"],
  ["Required for this visualization", "Nécessaire pour cette visualisation"],
  ["Results file data", "Données du fichier de résultats"],
  ["Results value", "Valeur des résultats"],
  ["Resume adding", "Reprendre l’ajout"],
  ["retrying", "réessayer"],
  ["Row groups", "Catégories de rangées"],
  ["Rows", "Rangées"],
  ["rows imported", "lignes importées"],
  ["Rows imported", "Lignes importées"],
  [
    "Rows in dataset after import",
    "Lignes dans l’ensemble de données après l’importation",
  ],
  [
    "Rows in dataset before import",
    "Lignes dans l’ensemble de données avant l’importation",
  ],
  ["Running", "En cours d'exécution"],
  ["Save", "Sauvegarder"],
  ["Save and close", "Sauvegarder et quitter"],
  ["Scale", "Échelle"],
  ["Search", "Recherche"],
  ["Secondary section text", "Texte de la section secondaire"],
  ["Section", "Section"],
  ["Select", "Sélectionner"],
  ["Select a figure to display", "Sélectionner une figure à afficher"],
  ["Select a visualization", "Sélectionner une visualisation"],
  ["Select visualization", "Sélectionner la visualisation"],
  ["Series (sub-bars)", "Series (sub-bars)"],
  ["Set custom colours", "Définir des couleurs personnalisées"],
  ["Settings", "Paramètres"],
  ["settings", "paramètres"],
  ["Show data labels", "Afficher les étiquettes de données"],
  ["Show page numbers", "Afficher la pagination"],
  ["slide", "diapositive"],
  ["Slide deck", "Présentation (diapositives)"],
  ["Slide type", "Type de diapositive"],
  ["slides", "diapositives"],
  ["Sort indicator values", "Trier les valeurs des indicateurs"],
  ["Special coverage chart", "Graphique de couverture spéciale"],
  [
    "Special percent change chart",
    "Graphique de variation spéciale en pourcentage",
  ],
  ["Stacked bars", "Histogramme empilé"],
  ["Start new import", "Lancer une nouvelle importation"],
  ["Stay on this report", "Restez sur ce rapport"],
  [
    "Stretch image to fit container",
    "Étendre l'image pour l'adapter au conteneur",
  ],
  ["Style", "Style"],
  ["Sub-caption", "Sous-titre"],
  ["Sub-header text", "Texte de sous-en-tête"],
  ["Sub-title text", "Texte de sous-titre"],
  ["Table", "Tableau"],
  ["Text", "Texte"],
  ["Text background", "Arrière-plan du texte"],
  ["Text size", "Taille du texte"],
  ["This project", "Ce projet"],
  ["This report", "Ce rapport"],
  [
    "This user is automatically a project editor because they are an instance administrator",
    "Cet utilisateur est automatiquement éditeur de ce projet en tant qu’administrateur de l’instance",
  ],
  ["Time period", "Période"],
  ["Timeseries", "Série chronologique"],
  ["to col", "vers la colonne"],
  ["to row", "vers la ligne"],
  ["Top", "Haut"],
  ["Transparent", "Transparent"],
  ["Update project permissions", "Mettre à jour les droits du projet"],
  [
    "Upload new csv file to use",
    "Téléverser un nouveau fichier CSV à utiliser",
  ],
  [
    "Use additional visualization scaling",
    "Appliquer un redimensionnement supplémentaire de la visualisation",
  ],
  ["Use policy brief footer", "Utiliser le pied de page de la note politique"],
  ["Use policy brief header", "Utiliser l’en-tête de la note politique"],
  ["Use slide footer", "Utiliser le pied de page de la diapositive"],
  ["Use slide header", "Utiliser l’en-tête de la diapositive"],
  ["User profile for", "Profil utilisateur de"],
  ["Users", "Utilisateurs"],
  ["Vertical tick labels", "Étiquettes de graduation verticales"],
  ["VISUALIZATION", "VISUALISATION"],
  ["Visualization", "Visualisation"],
  ["Visualization name", "Nom de la visualisation"],
  ["Visualizations", "Visualisations"],
  ["Watermark", "Filigrane"],
  ["Watermark text", "Texte du filigrane"],
  [
    "What do you want to do after duplicating?",
    "Que voulez-vous faire après la duplication ?",
  ],
  [
    "Which project should this report be duplicated into?",
    "Dans quel projet ce rapport doit-il être dupliqué ?",
  ],
  [
    "Which report should this page be duplicated into?",
    "Dans quel rapport cette page doit-il être dupliqué ?",
  ],
  [
    "Which report should this slide be duplicated into?",
    "Dans quel rapport cette diapositive doit-il être dupliqué ?",
  ],
  ["White", "Blanc"],
  ["With margins", "Avec marges"],
  ["Yearly", "Annuellement"],
  ["Yes", "Oui"],
  [
    "You have two disaggregators with the same display option",
    "Vous disposez de deux désagrégateurs avec la même option d'affichage",
  ],
  [
    "You must save before downloading figures",
    "Sauvegarde nécessaire avant téléchargement des figures",
  ],
  ["You must select a replicant", "Un réplicant doit être sélectionné"],
  ["+10% or above", "Supérieur ou égal à +10 %"],
  ["-10% to +10%", "-10% à +10%"],
  ["-10% or below", "Inférieur ou égal à -10 %"],
  [
    "DISCLAIMER: These results use routine data to provide rigorous, but not official estimates. They should be interpreted considering any data quality or representation limitations, including data quality findings and any other country specific factors",
    "AVERTISSEMENT: Ces résultats s'appuient sur des données d'exploitation courante\r\npour produire des estimations méthodologiques à caractère non officiel. Leur\r\ninterprétation doit tenir compte des limites inhérentes à la qualité et à la représentativité\r\ndes données sources, notamment des indicateurs de qualité et de tout facteur\r\ncontextuel propre au pays concerné.",
  ],
  [
    "Estimating service coverage from administrative data can provide more timely information on coverade trends or highlight data quality concerns. Numerators are the volumes reported in HMIS adiusted for data quality. Denominators are selected from UN proiections survey estimates or derived from HMIS volume for related indicators. National projections are made by applying HMIS trends to the most recent survey data. Subnational estimates are more sensitive to poor data quality, and projections from surveys are not calculated.",
    "L’estimation de la couverture des services à partir des données administratives peut\r\nfournir des informations plus récentes sur les tendances de couverture ou mettre en\r\névidence des problèmes de qualité des données. Les numérateurs correspondent aux\r\nvolumes déclarés dans le SGIS, ajustés en fonction de la qualité des données. Les\r\ndénominateurs sont sélectionnés à partir des projections de l'ONU, d’estimations issues\r\nd’enquêtes ou dérivés des volumes de données du SGIS pour des indicateurs\r\nconnexes. Les projections nationales sont établies en appliquant les tendances du\r\nSGIS aux données d’enquête les plus récentes. Les estimations infranationales sont\r\nplus sensibles aux données de mauvaise qualité ; et les projections basées sur les\r\nenquêtes ne sont pas calculées.",
  ],
  [
    "MICS data courtesy of UNICEF. Multiple Indicator Cluster Surveys (various rounds)\r\nNew York City, New York.",
    "Données MICS fournies par l'UNICEF. Enquêtes en grappes à indicateurs\r\nmultiples (différents cycles), New York, État de New York.",
  ],
  [
    "DHS data courtesy of ICF. Demographic and Health Surveys (various rounds).\r\nRockville, Maryland.",
    "Données de DHS fournies par l'ICF. Enquêtes démographiques et de santé\r\n(différentes cycles). Rockville, Maryland.",
  ],
  [
    "Sub-national level coverage estimates, prenatal consultation 1",
    "Estimations de couverture infranationales, Consultation prénatale 1",
  ],
  ["ANC1 is larger than ANC4", "Nombre de CPN1 supérieur au nombre de CPN4"],
  [
    "Delivery is approximately equal to BCG",
    "Nombre d'accouchements approximativement équivalent au nombre de BCG",
  ],
  [
    "Penta1 is larger than Penta 3",
    "Nombre de Penta1 supérieur au nombre de Penta3",
  ],
  [
    "Greater than 10% quarter-to-quarter decrease",
    "Diminution de plus de 10% d'un trimestre à l'autre",
  ],
  [
    "Greater than 10% quarter-to-quarter increase",
    "Augmentation de plus de 10% d'un trimestre à l'autre",
  ],
  ["Surplus", "Excédent"],
  ["Disruption", "Perturbation"],
  ["Actual", "Réel"],
  ["Expected", "Attendu"],
  [
    "Disruptions and surpluses in service volume, sub nationally",
    "Perturbations et excédents du volume de service, au niveau infranational",
  ],
  [
    "Change in service volume, quarterly",
    "Variation du volume de services, trimestrielle",
  ],
  [
    "Change in service volume, annually",
    "Variation du volume de services, annuelle",
  ],
  [
    "Actual vs expected number of services",
    "Nombre réel vs attendu de services (zone administrative 2)",
  ],
  ["Actual number of services reported", "Nombre réel de services rapportés"],
  ["Expected number of services", "Nombre de services attendus"],
  ["Number of services reported", "Nombre de services rapportés"],
  [
    "Number of services after outlier adjustment",
    "Nombre de services après ajustement des valeurs aberrantes",
  ],
  [
    "Number of services after completeness adjustment",
    "Nombre de services après ajustement pour complétude",
  ],
  [
    "Number of services after both outlier and completeness adjustment",
    "Nombre de services après ajustement des valeurs aberrantes et pour complétude",
  ],
  ["Last 12 months", "Les 12 derniers mois"],
  ["Last calendar year", "Dernière année civile"],
  ["Custom", "Personnalisé"],
  ["Aspect ratio", "Rapport hauteur/largeur"],
  ["Fit to area", "Ajuster à la zone"],
  ["Ideal for table", "Idéal pour table"],
  [
    "Allow vertical column headers",
    "Autoriser les en-têtes de colonnes verticales",
  ],
  ["Red-green", "Rouge-vert"],
  ["Blue-green", "Bleu-vert"],
  ["Single grey", "Gris simple"],
  [
    "In the above fields, you can use some special words to dynamically insert text.\\nUse DATE_RANGE or PLAGE_DE_DATES to insert the date range of the data shown in the figure. (Note that this currently only works for timeseries visualizations.)\\nUse REPLICANT to insert the full replicant name (e.g. an indicator, or an admin area). (Note that this only works if you have a disaggregator set for different charts.)\\nYou must spell these special words exactly correctly for them to work, including using capital letters and underscores, as above.",
    "Dans les champs ci-dessus, vous pouvez utiliser des mots spéciaux pour insérer dynamiquement du texte.\\nUtilisez DATE_RANGE ou PLAGE_DE_DATES pour insérer la plage de dates des données affichées dans la figure. (Notez que cela ne fonctionne actuellement que pour les visualisations de séries chronologiques.)\\nUtilisez REPLICANT pour insérer le nom complet du réplicant (par exemple, un indicateur ou une zone d'administration). (Notez que cela ne fonctionne que si vous avez défini un désagrégateur pour différents graphiques.)\\nVous devez orthographier ces mots spéciaux avec précision pour qu'ils fonctionnent, y compris en utilisant des majuscules et des traits de soulignement, comme indiqué ci-dessus.",
  ],
  ["Percent change", "Variation de pourcentage"],
]);
