FROM rocker/tidyverse:4.4.2
RUN R -q -e 'install.packages("scales")'
RUN R -q -e 'install.packages("lubridate")'
RUN R -q -e 'install.packages("zoo")'
RUN R -q -e 'install.packages("haven")'
RUN R -q -e 'install.packages("data.table")'
RUN R -q -e 'install.packages("fixest")'
RUN R -q -e 'install.packages("readxl")'
RUN R -q -e 'install.packages("MASS")'
