export { createIdGeneratorForLayout, generateUniqueBlockId } from "./_id_generation.ts";
export { DuplicateProductsModal } from "./duplicate_products_modal.tsx";
export { ancestors, childFolders, descendantIds, folderPathLabels, folderPathOptions } from "./folder_tree.ts";
export { PackageScopeChip } from "./package_scope_chip.tsx";
export { PackageScopeModal } from "./package_scope_modal.tsx";
export { createReportPaginator } from "./paginate_report.ts";
export type { ReportPaginator, ReportPaginatorDeps } from "./paginate_report.ts";
export { ProductSettings } from "./product_settings.tsx";
export { applyRebasedEdits, formatLineRanges, rebaseProposedEdits } from "./rebase_edits.ts";
export type { RebasedEdit, SkippedRange } from "./rebase_edits.ts";
export { ReportHtmlPreview } from "./report_html_preview.tsx";
export { ReportStyleEditor } from "./report_style_editor.tsx";
export type { ReportStyleEditorResult } from "./report_style_editor.tsx";
export { ReportFigureEmbed } from "./ReportFigureEmbed.tsx";
export type { FigureStaleContext } from "./ReportFigureEmbed.tsx";
export { ScopePicker, scopeSelectionFromStored, storedValueFromScopeSelection } from "./scope_picker.tsx";
export type { ScopeSelection } from "./scope_picker.tsx";
export { divSurface, iframeSurface, isSurfaceAtBottom, lineToPreviewTop, previewTopToLine, scrollSurfaceToBottom } from "./scroll_sync.ts";
export type { PreviewAnchor, PreviewSurface, PreviewSurfaceEvent } from "./scroll_sync.ts";
export { InsertFigureModal } from "./insert_figure/mod.ts";
export type { InsertFigureResult } from "./insert_figure/mod.ts";
