// Copyright 2023-2026, Tim Roberton, All rights reserved.
//
// ⚠️  EXTERNAL LIBRARY - Auto-synced from timroberton-panther
// ⚠️  DO NOT EDIT - Changes will be overwritten on next sync

import type { JSX } from "solid-js";

// The shared icon contract. Both icon sets (icons_tabler.tsx, icons_phosphor.tsx)
// conform to these keys; neither set is canonical over the other.
export type IconComponent = (p: { class?: string }) => JSX.Element;

export type IconName =
  | "alertCircle"
  | "arrowDown"
  | "arrowLeft"
  | "arrowRight"
  | "arrowUp"
  | "arrowsDiagonal"
  | "arrowsDiagonal2"
  | "arrowsDiagonalMinimize"
  | "arrowsDiagonalMinimize2"
  | "backspace"
  | "badge"
  | "box"
  | "calendar"
  | "chart"
  | "check"
  | "chevronDown"
  | "chevronLeft"
  | "chevronRight"
  | "chevronUp"
  | "circleX"
  | "clearAll"
  | "clock"
  | "code"
  | "copy"
  | "dashboard"
  | "database"
  | "databaseImport"
  | "document"
  | "download"
  | "eye"
  | "eyeOff"
  | "eraser"
  | "file"
  | "folder"
  | "gripVertical"
  | "help"
  | "helpSquare"
  | "import"
  | "info"
  | "infoSmall"
  | "infoSquare"
  | "layoutDashboard"
  | "layoutGrid"
  | "lifebuoy"
  | "lock"
  | "login"
  | "maximize"
  | "minimize"
  | "minus"
  | "moreVertical"
  | "move"
  | "package"
  | "pencil"
  | "photo"
  | "plus"
  | "presentation"
  | "presentationAnalytics"
  | "print"
  | "questionMark"
  | "redo"
  | "refresh"
  | "report"
  | "restore"
  | "rotate"
  | "save"
  | "search"
  | "selector"
  | "settings"
  | "settingsCog"
  | "slideshow"
  | "sparkles"
  | "switchHorizontal"
  | "text"
  | "transform"
  | "trash"
  | "undo"
  | "unlock"
  | "upload"
  | "user"
  | "userCircle"
  | "userPlus"
  | "users"
  | "versions"
  | "x";
