// ⚠️  THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by build_module_definitions.ts
// Last generated: 2025-12-17T07:38:50.035Z

// Define module IDs as a const array first
const MODULE_IDS = ["m001", "m002", "m003", "m004", "m005", "m006", "hfa001"] as const;
export type ModuleId = (typeof MODULE_IDS)[number];

export function getValidatedModuleId(id: string): ModuleId {
  if (!MODULE_IDS.includes(id as ModuleId)) {
    throw new Error("Bad module id");
  }
  return id as ModuleId;
}

// Now use ModuleId type in the module definitions
export const _POSSIBLE_MODULES: {
  id: ModuleId;
  label: string;
  prerequisiteModules: ModuleId[];
}[] = [
  { id: "m001", label: "M1. Data quality assessment", prerequisiteModules: [] },
  { id: "m002", label: "M2. Data quality adjustments", prerequisiteModules: ["m001"] },
  { id: "m003", label: "M3. Service utilization", prerequisiteModules: ["m001", "m002"] },
  { id: "m004", label: "M4. Coverage estimates", prerequisiteModules: ["m002"] },
  { id: "m005", label: "M5. Coverage estimates ~ new, part 1", prerequisiteModules: ["m002"] },
  { id: "m006", label: "M6. Coverage estimates ~ new, part 2", prerequisiteModules: ["m005"] },
  { id: "hfa001", label: "HFA001. Health facility assessment", prerequisiteModules: [] },
];
