// ⚠️  THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by build_module_definitions.ts
// Last generated: 2026-01-21T14:02:17.662Z

// Define module IDs as a const array first
const MODULE_IDS = ["m001", "m002", "m003", "m004", "m005", "m006", "hfa001"] as const;
export type ModuleId = (typeof MODULE_IDS)[number];

export function getValidatedModuleId(id: string): ModuleId {
  if (!MODULE_IDS.includes(id as ModuleId)) {
    throw new Error("Bad module id");
  }
  return id as ModuleId;
}

// Now use ModuleId type in the module definitions
export const _POSSIBLE_MODULES: {
  id: ModuleId;
  label: string;
  prerequisiteModules: ModuleId[];
}[] = [
  { id: "m001", label: "M1. Data quality assessment", prerequisiteModules: [] },
  { id: "m002", label: "M2. Data quality adjustments", prerequisiteModules: ["m001"] },
  { id: "m003", label: "M3. Service utilization", prerequisiteModules: ["m001", "m002"] },
  { id: "m004", label: "M4. Coverage estimates", prerequisiteModules: ["m002"] },
  { id: "m005", label: "M5. Coverage estimates ~ new, part 1", prerequisiteModules: ["m002"] },
  { id: "m006", label: "M6. Coverage estimates ~ new, part 2", prerequisiteModules: ["m005"] },
  { id: "hfa001", label: "HFA001. Health facility assessment", prerequisiteModules: [] },
];

// Metric ID to Module ID mapping
export const METRIC_TO_MODULE: Record<string, ModuleId> = {
  "hfa001-average": "hfa001",
  "hfa001-count": "hfa001",
  "hfa001-percentage": "hfa001",
  "hfa001-total": "hfa001",
  "m1-01-00": "m001",
  "m1-01-01": "m001",
  "m1-02-02": "m001",
  "m1-03-01": "m001",
  "m1-04-01": "m001",
  "m1-04-02": "m001",
  "m1-05-01": "m001",
  "m2-01-01": "m002",
  "m2-01-02": "m002",
  "m2-01-03": "m002",
  "m3-01-01": "m003",
  "m3-02-01": "m003",
  "m3-02-02": "m003",
  "m3-03-01": "m003",
  "m3-03-02": "m003",
  "m3-04-01": "m003",
  "m3-04-02": "m003",
  "m3-05-01": "m003",
  "m3-05-02": "m003",
  "m4-01-01": "m004",
  "m4-02-01": "m004",
  "m4-03-01": "m004",
  "m4a-01-01": "m005",
  "m4a-01-02": "m005",
  "m4a-01-03": "m005",
  "m4a-02-01": "m005",
  "m4a-02-02": "m005",
  "m4a-02-03": "m005",
  "m6-01-01": "m006",
  "m6-02-01": "m006",
  "m6-02-02": "m006",
  "m6-03-01": "m006",
  "m6-03-02": "m006",
};

export function getModuleIdForMetric(metricId: string): ModuleId {
  const moduleId = METRIC_TO_MODULE[metricId];
  if (!moduleId) {
    throw new Error(`Unknown metricId: ${metricId}. This may indicate a migration issue.`);
  }
  return moduleId;
}

// Results Object ID to Module ID mapping
export const RESULTS_OBJECT_TO_MODULE: Record<string, ModuleId> = {
  "HFA001_results.csv": "hfa001",
  "M1_output_completeness.csv": "m001",
  "M1_output_consistency_geo.csv": "m001",
  "M1_output_dqa.csv": "m001",
  "M1_output_outlier_list.csv": "m001",
  "M1_output_outliers.csv": "m001",
  "M2_adjusted_data.csv": "m002",
  "M2_adjusted_data_admin_area.csv": "m002",
  "M2_adjusted_data_national.csv": "m002",
  "M2_low_volume_exclusions.csv": "m002",
  "M3_all_indicators_shortfalls_admin_area_1.csv": "m003",
  "M3_all_indicators_shortfalls_admin_area_2.csv": "m003",
  "M3_all_indicators_shortfalls_admin_area_3.csv": "m003",
  "M3_all_indicators_shortfalls_admin_area_4.csv": "m003",
  "M3_chartout.csv": "m003",
  "M3_disruptions_analysis_admin_area_1.csv": "m003",
  "M3_disruptions_analysis_admin_area_2.csv": "m003",
  "M3_disruptions_analysis_admin_area_3.csv": "m003",
  "M3_disruptions_analysis_admin_area_4.csv": "m003",
  "M3_service_utilization.csv": "m003",
  "M4_coverage_estimation.csv": "m004",
  "M4_coverage_estimation_admin_area_2.csv": "m004",
  "M4_coverage_estimation_admin_area_3.csv": "m004",
  "M4_selected_denominator_per_indicator.csv": "m004",
  "M5_combined_results_admin2.csv": "m005",
  "M5_combined_results_admin3.csv": "m005",
  "M5_combined_results_national.csv": "m005",
  "M5_denominators_admin2.csv": "m005",
  "M5_denominators_admin3.csv": "m005",
  "M5_denominators_national.csv": "m005",
  "M5_selected_denominator_per_indicator.csv": "m005",
  "M6_coverage_estimation_admin2.csv": "m006",
  "M6_coverage_estimation_admin3.csv": "m006",
  "M6_coverage_estimation_national.csv": "m006",
};

export function getModuleIdForResultsObject(resultsObjectId: string): ModuleId {
  const moduleId = RESULTS_OBJECT_TO_MODULE[resultsObjectId];
  if (!moduleId) {
    throw new Error(`Unknown resultsObjectId: ${resultsObjectId}. This may indicate a migration issue.`);
  }
  return moduleId;
}

// Static metric data for building fetchConfig client-side
export const METRIC_STATIC_DATA: Record<string, {
  resultsObjectId: string;
  valueProps: string[];
  valueFunc: "SUM" | "AVG" | "COUNT" | "MIN" | "MAX" | "identity";
  formatAs: "percent" | "number";
}> = {
  "hfa001-average": { resultsObjectId: "HFA001_results.csv", valueProps: ["value"], valueFunc: "AVG", formatAs: "number" },
  "hfa001-count": { resultsObjectId: "HFA001_results.csv", valueProps: ["value"], valueFunc: "COUNT", formatAs: "number" },
  "hfa001-percentage": { resultsObjectId: "HFA001_results.csv", valueProps: ["value"], valueFunc: "AVG", formatAs: "percent" },
  "hfa001-total": { resultsObjectId: "HFA001_results.csv", valueProps: ["value"], valueFunc: "SUM", formatAs: "number" },
  "m1-01-00": { resultsObjectId: "M1_output_outliers.csv", valueProps: ["facility_id"], valueFunc: "COUNT", formatAs: "number" },
  "m1-01-01": { resultsObjectId: "M1_output_outliers.csv", valueProps: ["outlier_flag"], valueFunc: "AVG", formatAs: "percent" },
  "m1-02-02": { resultsObjectId: "M1_output_completeness.csv", valueProps: ["completeness_flag"], valueFunc: "AVG", formatAs: "percent" },
  "m1-03-01": { resultsObjectId: "M1_output_consistency_geo.csv", valueProps: ["sconsistency"], valueFunc: "AVG", formatAs: "percent" },
  "m1-04-01": { resultsObjectId: "M1_output_dqa.csv", valueProps: ["dqa_score"], valueFunc: "AVG", formatAs: "percent" },
  "m1-04-02": { resultsObjectId: "M1_output_dqa.csv", valueProps: ["dqa_mean"], valueFunc: "AVG", formatAs: "percent" },
  "m1-05-01": { resultsObjectId: "M1_output_outlier_list.csv", valueProps: ["count"], valueFunc: "SUM", formatAs: "number" },
  "m2-01-01": { resultsObjectId: "M2_adjusted_data.csv", valueProps: ["pct_change"], valueFunc: "identity", formatAs: "percent" },
  "m2-01-02": { resultsObjectId: "M2_adjusted_data.csv", valueProps: ["pct_change"], valueFunc: "identity", formatAs: "percent" },
  "m2-01-03": { resultsObjectId: "M2_adjusted_data.csv", valueProps: ["pct_change"], valueFunc: "identity", formatAs: "percent" },
  "m3-01-01": { resultsObjectId: "M3_service_utilization.csv", valueProps: ["count_final_none","count_final_outliers","count_final_completeness","count_final_both"], valueFunc: "SUM", formatAs: "number" },
  "m3-02-01": { resultsObjectId: "M3_disruptions_analysis_admin_area_1.csv", valueProps: ["count_sum","count_expected_if_above_diff_threshold"], valueFunc: "SUM", formatAs: "number" },
  "m3-02-02": { resultsObjectId: "M3_disruptions_analysis_admin_area_1.csv", valueProps: ["pct_diff"], valueFunc: "identity", formatAs: "percent" },
  "m3-03-01": { resultsObjectId: "M3_disruptions_analysis_admin_area_2.csv", valueProps: ["count_sum","count_expected_if_above_diff_threshold"], valueFunc: "SUM", formatAs: "number" },
  "m3-03-02": { resultsObjectId: "M3_disruptions_analysis_admin_area_2.csv", valueProps: ["pct_diff"], valueFunc: "identity", formatAs: "percent" },
  "m3-04-01": { resultsObjectId: "M3_disruptions_analysis_admin_area_3.csv", valueProps: ["count_sum","count_expected_if_above_diff_threshold"], valueFunc: "SUM", formatAs: "number" },
  "m3-04-02": { resultsObjectId: "M3_disruptions_analysis_admin_area_3.csv", valueProps: ["pct_diff"], valueFunc: "identity", formatAs: "percent" },
  "m3-05-01": { resultsObjectId: "M3_disruptions_analysis_admin_area_4.csv", valueProps: ["count_sum","count_expected_if_above_diff_threshold"], valueFunc: "SUM", formatAs: "number" },
  "m3-05-02": { resultsObjectId: "M3_disruptions_analysis_admin_area_4.csv", valueProps: ["pct_diff"], valueFunc: "identity", formatAs: "percent" },
  "m4-01-01": { resultsObjectId: "M4_coverage_estimation.csv", valueProps: ["coverage_original_estimate","coverage_avgsurveyprojection","coverage_cov"], valueFunc: "AVG", formatAs: "percent" },
  "m4-02-01": { resultsObjectId: "M4_coverage_estimation_admin_area_2.csv", valueProps: ["coverage_cov"], valueFunc: "AVG", formatAs: "percent" },
  "m4-03-01": { resultsObjectId: "M4_coverage_estimation_admin_area_3.csv", valueProps: ["coverage_cov"], valueFunc: "AVG", formatAs: "percent" },
  "m4a-01-01": { resultsObjectId: "M5_denominators_national.csv", valueProps: ["value"], valueFunc: "AVG", formatAs: "number" },
  "m4a-01-02": { resultsObjectId: "M5_denominators_admin2.csv", valueProps: ["value"], valueFunc: "AVG", formatAs: "number" },
  "m4a-01-03": { resultsObjectId: "M5_denominators_admin3.csv", valueProps: ["value"], valueFunc: "AVG", formatAs: "number" },
  "m4a-02-01": { resultsObjectId: "M5_combined_results_national.csv", valueProps: ["value"], valueFunc: "AVG", formatAs: "percent" },
  "m4a-02-02": { resultsObjectId: "M5_combined_results_admin2.csv", valueProps: ["value"], valueFunc: "AVG", formatAs: "percent" },
  "m4a-02-03": { resultsObjectId: "M5_combined_results_admin3.csv", valueProps: ["value"], valueFunc: "AVG", formatAs: "percent" },
  "m6-01-01": { resultsObjectId: "M6_coverage_estimation_national.csv", valueProps: ["coverage_original_estimate","coverage_avgsurveyprojection","coverage_cov"], valueFunc: "AVG", formatAs: "percent" },
  "m6-02-01": { resultsObjectId: "M6_coverage_estimation_admin2.csv", valueProps: ["coverage_original_estimate","coverage_avgsurveyprojection","coverage_cov"], valueFunc: "AVG", formatAs: "percent" },
  "m6-02-02": { resultsObjectId: "M6_coverage_estimation_admin2.csv", valueProps: ["coverage_cov"], valueFunc: "AVG", formatAs: "percent" },
  "m6-03-01": { resultsObjectId: "M6_coverage_estimation_admin3.csv", valueProps: ["coverage_original_estimate","coverage_avgsurveyprojection","coverage_cov"], valueFunc: "AVG", formatAs: "percent" },
  "m6-03-02": { resultsObjectId: "M6_coverage_estimation_admin3.csv", valueProps: ["coverage_cov"], valueFunc: "AVG", formatAs: "percent" },
};

export function getMetricStaticData(metricId: string) {
  const data = METRIC_STATIC_DATA[metricId];
  if (!data) {
    throw new Error(`Unknown metricId: ${metricId}. This may indicate a migration issue.`);
  }
  return data;
}
