import { join } from "@std/path";
import {
  getValidatedModuleId,
  type APIResponseWithData,
  type ModuleConfigSelections,
  type RunCatalogDetail,
  type RunModuleFileListing,
} from "lib";
import { parseModuleConfigSelections } from "../db/project/modules.ts";
import {
  _MODULE_LOG_FILE_NAME,
  _MODULE_SCRIPT_FILE_NAME,
} from "../exposed_env_vars.ts";
import { getRunManifestCached } from "./manifest_cache.ts";
import { runDirPath } from "./run_paths.ts";

// Reading a package's INTERNALS — the generated R script, the execution log,
// and the raw output files under runs/{runId}/outputs/{moduleId}.
//
// This module is the single implementation, deliberately, because the same
// bytes are served through two mounts with two different permission models
// (PLAN_RESULTS_RUNS, Tim's ruling 2026-07-30):
//   - the INSTANCE catalogue (routes/instance/run_generation.ts) takes a runId
//     and is `can_configure_data` — an admin browsing packages, including ones
//     attached to no project at all;
//   - a PROJECT (routes/project/results_package.ts) never names a runId. It
//     resolves the run from `projects.run_id` and gates each kind of content on
//     the per-project bit built for it: `can_view_script_code` for the script,
//     `can_view_logs` for the log, `can_view_data` for the raw files.
// What a package contains does not depend on who is asking; only the chrome
// and the guard do. Hence: one reader, two guards.
//
// Path safety is enforced HERE rather than at each route, because these are
// the only functions that turn caller-supplied strings into paths under the
// runs volume. runId must be a UUID, moduleId must be in the module registry,
// and a file name may not contain a path separator or `..` — a traversal
// attempt is a typed failure, never a read outside the module's own dir.

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function resolveOutputsDir(
  runId: string,
  moduleId: string,
): { success: true; dir: string } | { success: false; err: string } {
  if (!UUID_RE.test(runId)) {
    return { success: false, err: "Invalid results package id" };
  }
  try {
    getValidatedModuleId(moduleId);
  } catch {
    return { success: false, err: "Unknown module" };
  }
  return { success: true, dir: join(runDirPath(runId), "outputs", moduleId) };
}

// A run written before this module existed, a backfill-synthesized package (no
// script or log — it was never generated by the wizard), or a module that
// produced no files all answer with a typed message rather than an error page.
async function readOutputText(
  runId: string,
  moduleId: string,
  fileName: string,
  absentMessage: string,
): Promise<APIResponseWithData<string>> {
  const resolved = resolveOutputsDir(runId, moduleId);
  if (resolved.success === false) {
    return resolved;
  }
  try {
    return { success: true, data: await Deno.readTextFile(join(resolved.dir, fileName)) };
  } catch (e) {
    if (e instanceof Deno.errors.NotFound) {
      return { success: false, err: absentMessage };
    }
    return {
      success: false,
      err: "Problem reading this results package file: " +
        (e instanceof Error ? e.message : ""),
    };
  }
}

export async function readRunModuleScript(
  runId: string,
  moduleId: string,
): Promise<APIResponseWithData<{ script: string }>> {
  const res = await readOutputText(
    runId,
    moduleId,
    _MODULE_SCRIPT_FILE_NAME,
    "No script in this results package for this module.",
  );
  return res.success === false ? res : { success: true, data: { script: res.data } };
}

export async function readRunModuleLogs(
  runId: string,
  moduleId: string,
): Promise<APIResponseWithData<{ logs: string }>> {
  const res = await readOutputText(
    runId,
    moduleId,
    _MODULE_LOG_FILE_NAME,
    "No execution log in this results package for this module.",
  );
  return res.success === false ? res : { success: true, data: { logs: res.data } };
}

// An absent dir is an empty listing, not an error: a package legitimately has
// no outputs for a module it reused nothing from, and the caller renders the
// same "no files" state either way.
export async function listRunModuleFiles(
  runId: string,
  moduleId: string,
): Promise<APIResponseWithData<RunModuleFileListing>> {
  const resolved = resolveOutputsDir(runId, moduleId);
  if (resolved.success === false) {
    return resolved;
  }
  const files: RunModuleFileListing["files"] = [];
  try {
    for await (const entry of Deno.readDir(resolved.dir)) {
      if (!entry.isFile) continue;
      const stat = await Deno.stat(join(resolved.dir, entry.name));
      files.push({ name: entry.name, sizeBytes: stat.size });
    }
  } catch (e) {
    if (!(e instanceof Deno.errors.NotFound)) {
      return {
        success: false,
        err: "Problem listing results package files: " +
          (e instanceof Error ? e.message : ""),
      };
    }
  }
  files.sort((a, b) => a.name.localeCompare(b.name));
  return { success: true, data: { files } };
}

// The catalogue's master–detail body for one READY package: per-module
// settings resolved from the manifest's configSelections (the
// formatModuleSettingsForAI precedent — label from the parameter definition,
// select values displayed as their option label) plus the outputs-dir file
// listing. Manifest-gated: generating/failed runs have no manifest and are
// served by the progress-derived UI instead.
export async function readRunCatalogDetail(
  runId: string,
): Promise<APIResponseWithData<RunCatalogDetail>> {
  if (!UUID_RE.test(runId)) {
    return { success: false, err: "Invalid results package id" };
  }
  let manifest;
  try {
    manifest = await getRunManifestCached(runId);
  } catch (e) {
    return {
      success: false,
      err: "This results package has no manifest to read settings from: " +
        (e instanceof Error ? e.message : ""),
    };
  }
  try {
    const modules: RunCatalogDetail["modules"] = [];
    for (const mod of manifest.modules) {
      const filesRes = await listRunModuleFiles(runId, mod.id);
      if (filesRes.success === false) {
        return filesRes;
      }
      modules.push({
        moduleId: mod.id,
        settings: resolveModuleSettings(mod.configSelections),
        files: filesRes.data.files,
      });
    }
    return { success: true, data: { modules } };
  } catch (e) {
    return {
      success: false,
      err: "Problem reading this results package's settings: " +
        (e instanceof Error ? e.message : ""),
    };
  }
}

function resolveModuleSettings(
  configSelectionsJson: string | null,
): { label: string; value: string }[] {
  if (configSelectionsJson === null) {
    return [];
  }
  const configSelections: ModuleConfigSelections = parseModuleConfigSelections(
    configSelectionsJson,
  );
  return Object.entries(configSelections.parameterSelections).map(
    ([key, value]) => {
      const param = configSelections.parameterDefinitions.find(
        (d) => d.replacementString === key,
      );
      const displayValue = param?.input.inputType === "select"
        ? param.input.options.find((o) => o.value === value)?.label ?? value
        : value;
      return { label: param?.description ?? key, value: displayValue };
    },
  );
}

// Resolves ONE output file for download. Returns the absolute path plus its
// size so the caller can stream it with a Content-Length; the caller owns the
// response, this owns the safety.
export async function resolveRunModuleFileForDownload(
  runId: string,
  moduleId: string,
  fileName: string,
): Promise<APIResponseWithData<{ path: string; sizeBytes: number }>> {
  const resolved = resolveOutputsDir(runId, moduleId);
  if (resolved.success === false) {
    return resolved;
  }
  if (
    fileName.length === 0 ||
    fileName.includes("/") ||
    fileName.includes("\\") ||
    fileName.includes("\0") ||
    fileName === "." ||
    fileName === ".."
  ) {
    return { success: false, err: "Invalid file name" };
  }
  const path = join(resolved.dir, fileName);
  try {
    const stat = await Deno.stat(path);
    if (!stat.isFile) {
      return { success: false, err: "Not a file" };
    }
    return { success: true, data: { path, sizeBytes: stat.size } };
  } catch (e) {
    if (e instanceof Deno.errors.NotFound) {
      return {
        success: false,
        err: "No such file in this results package.",
      };
    }
    return {
      success: false,
      err: "Problem reading this results package file: " +
        (e instanceof Error ? e.message : ""),
    };
  }
}
