// GENERATED by `deno task build:help-buttons` — DO NOT EDIT.
// Source: wb-fastr-site help tags (<!-- help#id -->). See DOC_HELP_BUTTONS.md.

import type { HelpTarget } from "./types.ts";

export const HELP_TARGETS = {
  "viz-create": {
    page: "user-guide/visualizations",
    anchor: { en: "creating-a-visualization", fr: "créer-une-visualisation" },
    title: { en: "Creating a visualization", fr: "Créer une visualisation" },
    summary: { en: "Every visualization starts with a metric. Metrics are the analytical outputs produced by your modules - things like \"ANC1 coverage rate\" or \"data completeness score.\" When you create a visualization,…", fr: "Chaque visualisation commence par un indicateur. Les indicateurs sont les résultats analytiques produits par vos modules - des éléments comme le « taux de couverture CPN1 » ou le « score de…" },
  },
  "viz-data-tab": {
    page: "user-guide/visualizations",
    anchor: { en: "data-tab", fr: "onglet-données" },
    title: { en: "Data tab", fr: "Onglet Données" },
    summary: { en: "The Data tab controls what information appears in the visualization. This is where you narrow the time range, add or remove disaggregations, or filter to specific values. Period filters let you focus…", fr: "L'onglet Données contrôle quelles informations apparaissent dans la visualisation. C'est ici que vous restreignez la plage temporelle, ajoutez ou supprimez des désagrégations, ou filtrez sur des…" },
  },
  "viz-share-link": {
    page: "user-guide/visualizations",
    anchor: { en: "sharing-a-link", fr: "partager-un-lien" },
    title: { en: "Sharing a link", fr: "Partager un lien" },
    summary: { en: "You can create a public link that lets anyone view a visualization without logging in. Click Share, toggle sharing on, and copy the link. This is useful for sharing with stakeholders who don't have…", fr: "Vous pouvez créer un lien public permettant à quiconque de consulter une visualisation sans se connecter. Cliquez sur Partager, activez le partage et copiez le lien. C'est utile pour partager avec…" },
  },
} as const satisfies Record<string, HelpTarget>;

export type HelpId = keyof typeof HELP_TARGETS;
