// Copyright 2023-2025, Tim Roberton, All rights reserved.
//
// ⚠️  EXTERNAL LIBRARY - Auto-synced from timroberton-panther
// ⚠️  DO NOT EDIT - Changes will be overwritten on next sync

export const FONT_MAP_TTF = {
  "FiraSans-400-italic": "fira-sans/FiraSans-Italic.ttf",
  "FiraSans-400-normal": "fira-sans/FiraSans-Regular.ttf",
  "FiraSans-700-italic": "fira-sans/FiraSans-BoldItalic.ttf",
  "FiraSans-700-normal": "fira-sans/FiraSans-Bold.ttf",
  "FiraSansExtraBold-800-italic": "fira-sans/FiraSans-ExtraBoldItalic.ttf",
  "FiraSansExtraBold-800-normal": "fira-sans/FiraSans-ExtraBold.ttf",
  "FiraSansExtraLight-200-italic": "fira-sans/FiraSans-ExtraLightItalic.ttf",
  "FiraSansExtraLight-200-normal": "fira-sans/FiraSans-ExtraLight.ttf",
  "FiraSansLight-300-italic": "fira-sans/FiraSans-LightItalic.ttf",
  "FiraSansLight-300-normal": "fira-sans/FiraSans-Light.ttf",
  "FiraSansMedium-500-italic": "fira-sans/FiraSans-MediumItalic.ttf",
  "FiraSansMedium-500-normal": "fira-sans/FiraSans-Medium.ttf",
  "FiraSansSemiBold-600-italic": "fira-sans/FiraSans-SemiBoldItalic.ttf",
  "FiraSansSemiBold-600-normal": "fira-sans/FiraSans-SemiBold.ttf",
  "FiraSansThin-100-italic": "fira-sans/FiraSans-ThinItalic.ttf",
  "FiraSansThin-100-normal": "fira-sans/FiraSans-Thin.ttf",
  "Gibson-400-italic": "gibson/Gibson-Italic.ttf",
  "Gibson-400-normal": "gibson/Gibson-Regular.ttf",
  "Gibson-700-italic": "gibson/Gibson-BoldItalic.ttf",
  "Gibson-700-normal": "gibson/Gibson-Bold.ttf",
  "GibsonBook-300-italic": "gibson/Gibson-BookItalic.ttf",
  "GibsonBook-300-normal": "gibson/Gibson-Book.ttf",
  "GibsonExtraBold-800-italic": "gibson/Gibson-ExtraBoldItalic.ttf",
  "GibsonExtraBold-800-normal": "gibson/Gibson-ExtraBold.ttf",
  "GibsonHeavy-900-italic": "gibson/Gibson-HeavyItalic.ttf",
  "GibsonHeavy-900-normal": "gibson/Gibson-Heavy.ttf",
  "GibsonLight-200-italic": "gibson/Gibson-LightItalic.ttf",
  "GibsonLight-200-normal": "gibson/Gibson-Light.ttf",
  "GibsonMedium-500-italic": "gibson/Gibson-MediumItalic.ttf",
  "GibsonMedium-500-normal": "gibson/Gibson-Medium.ttf",
  "GibsonSemiBold-600-italic": "gibson/Gibson-SemiBoldItalic.ttf",
  "GibsonSemiBold-600-normal": "gibson/Gibson-SemiBold.ttf",
  "GibsonThin-100-italic": "gibson/Gibson-ThinItalic.ttf",
  "GibsonThin-100-normal": "gibson/Gibson-Thin.ttf",
  "Inter-100-italic": "inter/Inter-ThinItalic.ttf",
  "Inter-100-normal": "inter/Inter-Thin.ttf",
  "Inter-200-italic": "inter/Inter-ExtraLightItalic.ttf",
  "Inter-200-normal": "inter/Inter-ExtraLight.ttf",
  "Inter-300-italic": "inter/Inter-LightItalic.ttf",
  "Inter-300-normal": "inter/Inter-Light.ttf",
  "Inter-400-italic": "inter/Inter-Italic.ttf",
  "Inter-400-normal": "inter/Inter-Regular.ttf",
  "Inter-500-italic": "inter/Inter-MediumItalic.ttf",
  "Inter-500-normal": "inter/Inter-Medium.ttf",
  "Inter-600-italic": "inter/Inter-SemiBoldItalic.ttf",
  "Inter-600-normal": "inter/Inter-SemiBold.ttf",
  "Inter-700-italic": "inter/Inter-BoldItalic.ttf",
  "Inter-700-normal": "inter/Inter-Bold.ttf",
  "Inter-800-italic": "inter/Inter-ExtraBoldItalic.ttf",
  "Inter-800-normal": "inter/Inter-ExtraBold.ttf",
  "Inter-900-italic": "inter/Inter-BlackItalic.ttf",
  "Inter-900-normal": "inter/Inter-Black.ttf",
  "InterDisplay-100-italic": "inter/InterDisplay-ThinItalic.ttf",
  "InterDisplay-100-normal": "inter/InterDisplay-Thin.ttf",
  "InterDisplay-200-italic": "inter/InterDisplay-ExtraLightItalic.ttf",
  "InterDisplay-200-normal": "inter/InterDisplay-ExtraLight.ttf",
  "InterDisplay-300-italic": "inter/InterDisplay-LightItalic.ttf",
  "InterDisplay-300-normal": "inter/InterDisplay-Light.ttf",
  "InterDisplay-400-italic": "inter/InterDisplay-Italic.ttf",
  "InterDisplay-400-normal": "inter/InterDisplay-Regular.ttf",
  "InterDisplay-500-italic": "inter/InterDisplay-MediumItalic.ttf",
  "InterDisplay-500-normal": "inter/InterDisplay-Medium.ttf",
  "InterDisplay-600-italic": "inter/InterDisplay-SemiBoldItalic.ttf",
  "InterDisplay-600-normal": "inter/InterDisplay-SemiBold.ttf",
  "InterDisplay-700-italic": "inter/InterDisplay-BoldItalic.ttf",
  "InterDisplay-700-normal": "inter/InterDisplay-Bold.ttf",
  "InterDisplay-800-italic": "inter/InterDisplay-ExtraBoldItalic.ttf",
  "InterDisplay-800-normal": "inter/InterDisplay-ExtraBold.ttf",
  "InterDisplay-900-italic": "inter/InterDisplay-BlackItalic.ttf",
  "InterDisplay-900-normal": "inter/InterDisplay-Black.ttf",
  "Merriweather-400-italic": "merriweather/Merriweather-Italic.ttf",
  "Merriweather-400-normal": "merriweather/Merriweather-Regular.ttf",
  "Merriweather-700-italic": "merriweather/Merriweather-BoldItalic.ttf",
  "Merriweather-700-normal": "merriweather/Merriweather-Bold.ttf",
  "MerriweatherBlack-900-italic": "merriweather/Merriweather-BlackItalic.ttf",
  "MerriweatherBlack-900-normal": "merriweather/Merriweather-Black.ttf",
  "MerriweatherLight-300-italic": "merriweather/Merriweather-LightItalic.ttf",
  "MerriweatherLight-300-normal": "merriweather/Merriweather-Light.ttf",
  "NotoSansEthiopic-100-normal": "noto-sans-ethiopic/NotoSansEthiopic-Thin.ttf",
  "NotoSansEthiopic-200-normal":
    "noto-sans-ethiopic/NotoSansEthiopic-ExtraLight.ttf",
  "NotoSansEthiopic-300-normal":
    "noto-sans-ethiopic/NotoSansEthiopic-Light.ttf",
  "NotoSansEthiopic-400-normal":
    "noto-sans-ethiopic/NotoSansEthiopic-Regular.ttf",
  "NotoSansEthiopic-500-normal":
    "noto-sans-ethiopic/NotoSansEthiopic-Medium.ttf",
  "NotoSansEthiopic-600-normal":
    "noto-sans-ethiopic/NotoSansEthiopic-SemiBold.ttf",
  "NotoSansEthiopic-700-normal": "noto-sans-ethiopic/NotoSansEthiopic-Bold.ttf",
  "NotoSansEthiopic-800-normal":
    "noto-sans-ethiopic/NotoSansEthiopic-ExtraBold.ttf",
  "NotoSansEthiopic-900-normal":
    "noto-sans-ethiopic/NotoSansEthiopic-Black.ttf",
  "Poppins-100-italic": "poppins/Poppins-ThinItalic.ttf",
  "Poppins-100-normal": "poppins/Poppins-Thin.ttf",
  "Poppins-200-italic": "poppins/Poppins-ExtraLightItalic.ttf",
  "Poppins-200-normal": "poppins/Poppins-ExtraLight.ttf",
  "Poppins-300-italic": "poppins/Poppins-LightItalic.ttf",
  "Poppins-300-normal": "poppins/Poppins-Light.ttf",
  "Poppins-400-italic": "poppins/Poppins-Italic.ttf",
  "Poppins-400-normal": "poppins/Poppins-Regular.ttf",
  "Poppins-500-italic": "poppins/Poppins-MediumItalic.ttf",
  "Poppins-500-normal": "poppins/Poppins-Medium.ttf",
  "Poppins-600-italic": "poppins/Poppins-SemiBoldItalic.ttf",
  "Poppins-600-normal": "poppins/Poppins-SemiBold.ttf",
  "Poppins-700-italic": "poppins/Poppins-BoldItalic.ttf",
  "Poppins-700-normal": "poppins/Poppins-Bold.ttf",
  "Poppins-800-italic": "poppins/Poppins-ExtraBoldItalic.ttf",
  "Poppins-800-normal": "poppins/Poppins-ExtraBold.ttf",
  "Poppins-900-italic": "poppins/Poppins-BlackItalic.ttf",
  "Poppins-900-normal": "poppins/Poppins-Black.ttf",
  "Roboto-400-italic": "roboto/Roboto-Italic.ttf",
  "Roboto-400-normal": "roboto/Roboto-Regular.ttf",
  "Roboto-700-italic": "roboto/Roboto-BoldItalic.ttf",
  "Roboto-700-normal": "roboto/Roboto-Bold.ttf",
  "RobotoBlack-900-italic": "roboto/Roboto-BlackItalic.ttf",
  "RobotoBlack-900-normal": "roboto/Roboto-Black.ttf",
  "RobotoLight-300-italic": "roboto/Roboto-LightItalic.ttf",
  "RobotoLight-300-normal": "roboto/Roboto-Light.ttf",
  "RobotoMedium-500-italic": "roboto/Roboto-MediumItalic.ttf",
  "RobotoMedium-500-normal": "roboto/Roboto-Medium.ttf",
  "RobotoMono-100-italic": "roboto-mono/RobotoMono-ThinItalic.ttf",
  "RobotoMono-100-normal": "roboto-mono/RobotoMono-Thin.ttf",
  "RobotoMono-200-italic": "roboto-mono/RobotoMono-ExtraLightItalic.ttf",
  "RobotoMono-200-normal": "roboto-mono/RobotoMono-ExtraLight.ttf",
  "RobotoMono-300-italic": "roboto-mono/RobotoMono-LightItalic.ttf",
  "RobotoMono-300-normal": "roboto-mono/RobotoMono-Light.ttf",
  "RobotoMono-400-italic": "roboto-mono/RobotoMono-Italic.ttf",
  "RobotoMono-400-normal": "roboto-mono/RobotoMono-Regular.ttf",
  "RobotoMono-500-italic": "roboto-mono/RobotoMono-MediumItalic.ttf",
  "RobotoMono-500-normal": "roboto-mono/RobotoMono-Medium.ttf",
  "RobotoMono-600-italic": "roboto-mono/RobotoMono-SemiBoldItalic.ttf",
  "RobotoMono-600-normal": "roboto-mono/RobotoMono-SemiBold.ttf",
  "RobotoMono-700-italic": "roboto-mono/RobotoMono-BoldItalic.ttf",
  "RobotoMono-700-normal": "roboto-mono/RobotoMono-Bold.ttf",
  "RobotoThin-100-italic": "roboto/Roboto-ThinItalic.ttf",
  "RobotoThin-100-normal": "roboto/Roboto-Thin.ttf",
  "Sarabun-100-italic": "sarabun/Sarabun-ThinItalic.ttf",
  "Sarabun-100-normal": "sarabun/Sarabun-Thin.ttf",
  "Sarabun-200-italic": "sarabun/Sarabun-ExtraLightItalic.ttf",
  "Sarabun-200-normal": "sarabun/Sarabun-ExtraLight.ttf",
  "Sarabun-300-italic": "sarabun/Sarabun-LightItalic.ttf",
  "Sarabun-300-normal": "sarabun/Sarabun-Light.ttf",
  "Sarabun-400-italic": "sarabun/Sarabun-Italic.ttf",
  "Sarabun-400-normal": "sarabun/Sarabun-Regular.ttf",
  "Sarabun-500-italic": "sarabun/Sarabun-MediumItalic.ttf",
  "Sarabun-500-normal": "sarabun/Sarabun-Medium.ttf",
  "Sarabun-600-italic": "sarabun/Sarabun-SemiBoldItalic.ttf",
  "Sarabun-600-normal": "sarabun/Sarabun-SemiBold.ttf",
  "Sarabun-700-italic": "sarabun/Sarabun-BoldItalic.ttf",
  "Sarabun-700-normal": "sarabun/Sarabun-Bold.ttf",
  "Sarabun-800-italic": "sarabun/Sarabun-ExtraBoldItalic.ttf",
  "Sarabun-800-normal": "sarabun/Sarabun-ExtraBold.ttf",
} as const;

export type FontIdTtf = keyof typeof FONT_MAP_TTF;
