// Copyright 2023-2025, Tim Roberton, All rights reserved.
//
// ⚠️  EXTERNAL LIBRARY - Auto-synced from timroberton-panther
// ⚠️  DO NOT EDIT - Changes will be overwritten on next sync

export const FONT_MAP_WOFF = {
  "Alegreya-400-italic": "alegreya/alegreya-v35-latin-italic.woff",
  "Alegreya-400-normal": "alegreya/alegreya-v35-latin-regular.woff",
  "Alegreya-500-italic": "alegreya/alegreya-v35-latin-500italic.woff",
  "Alegreya-500-normal": "alegreya/alegreya-v35-latin-500.woff",
  "Alegreya-600-italic": "alegreya/alegreya-v35-latin-600italic.woff",
  "Alegreya-600-normal": "alegreya/alegreya-v35-latin-600.woff",
  "Alegreya-700-italic": "alegreya/alegreya-v35-latin-700italic.woff",
  "Alegreya-700-normal": "alegreya/alegreya-v35-latin-700.woff",
  "Alegreya-800-italic": "alegreya/alegreya-v35-latin-800italic.woff",
  "Alegreya-800-normal": "alegreya/alegreya-v35-latin-800.woff",
  "Alegreya-900-italic": "alegreya/alegreya-v35-latin-900italic.woff",
  "Alegreya-900-normal": "alegreya/alegreya-v35-latin-900.woff",
  "Cambria-400-italic": "cambria/Cambria-Italic.woff",
  "Cambria-400-normal": "cambria/Cambria.woff",
  "Cambria-700-italic": "cambria/Cambria-BoldItalic.woff",
  "Cambria-700-normal": "cambria/Cambria-Bold.woff",
  "FiraMono-400-normal": "fira-mono/FiraMono-Regular.woff",
  "FiraMono-500-normal": "fira-mono/FiraMono-Medium.woff",
  "FiraMono-700-normal": "fira-mono/FiraMono-Bold.woff",
  "FiraSans-400-italic": "fira-sans/FiraSans-Italic.woff",
  "FiraSans-400-normal": "fira-sans/FiraSans-Regular.woff",
  "FiraSans-700-italic": "fira-sans/FiraSans-BoldItalic.woff",
  "FiraSans-700-normal": "fira-sans/FiraSans-Bold.woff",
  "FiraSansBlack-900-italic": "fira-sans/FiraSans-BlackItalic.woff",
  "FiraSansBlack-900-normal": "fira-sans/FiraSans-Black.woff",
  "FiraSansCondensed-100-italic":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-100italic.woff",
  "FiraSansCondensed-100-normal":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-100.woff",
  "FiraSansCondensed-200-italic":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-200italic.woff",
  "FiraSansCondensed-200-normal":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-200.woff",
  "FiraSansCondensed-300-italic":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-300italic.woff",
  "FiraSansCondensed-300-normal":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-300.woff",
  "FiraSansCondensed-400-italic":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-italic.woff",
  "FiraSansCondensed-400-normal":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-regular.woff",
  "FiraSansCondensed-500-italic":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-500italic.woff",
  "FiraSansCondensed-500-normal":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-500.woff",
  "FiraSansCondensed-600-italic":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-600italic.woff",
  "FiraSansCondensed-600-normal":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-600.woff",
  "FiraSansCondensed-700-italic":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-700italic.woff",
  "FiraSansCondensed-700-normal":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-700.woff",
  "FiraSansCondensed-800-italic":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-800italic.woff",
  "FiraSansCondensed-800-normal":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-800.woff",
  "FiraSansCondensed-900-italic":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-900italic.woff",
  "FiraSansCondensed-900-normal":
    "fira-sans-condensed/fira-sans-condensed-v10-latin-900.woff",
  "FiraSansExtraBold-800-italic": "fira-sans/FiraSans-ExtraBoldItalic.woff",
  "FiraSansExtraBold-800-normal": "fira-sans/FiraSans-ExtraBold.woff",
  "FiraSansExtraLight-200-italic": "fira-sans/FiraSans-ExtraLightItalic.woff",
  "FiraSansExtraLight-200-normal": "fira-sans/FiraSans-ExtraLight.woff",
  "FiraSansLight-300-italic": "fira-sans/FiraSans-LightItalic.woff",
  "FiraSansLight-300-normal": "fira-sans/FiraSans-Light.woff",
  "FiraSansMedium-500-italic": "fira-sans/FiraSans-MediumItalic.woff",
  "FiraSansMedium-500-normal": "fira-sans/FiraSans-Medium.woff",
  "FiraSansSemiBold-600-italic": "fira-sans/FiraSans-SemiBoldItalic.woff",
  "FiraSansSemiBold-600-normal": "fira-sans/FiraSans-SemiBold.woff",
  "FiraSansThin-100-italic": "fira-sans/FiraSans-ThinItalic.woff",
  "FiraSansThin-100-normal": "fira-sans/FiraSans-Thin.woff",
  "Gibson-400-italic": "gibson/Gibson-Italic.woff",
  "Gibson-400-normal": "gibson/Gibson-Regular.woff",
  "Gibson-700-italic": "gibson/Gibson-BoldItalic.woff",
  "Gibson-700-normal": "gibson/Gibson-Bold.woff",
  "GibsonBook-300-italic": "gibson/Gibson-BookItalic.woff",
  "GibsonBook-300-normal": "gibson/Gibson-Book.woff",
  "GibsonExtraBold-800-italic": "gibson/Gibson-ExtraBoldItalic.woff",
  "GibsonExtraBold-800-normal": "gibson/Gibson-ExtraBold.woff",
  "GibsonHeavy-900-italic": "gibson/Gibson-HeavyItalic.woff",
  "GibsonHeavy-900-normal": "gibson/Gibson-Heavy.woff",
  "GibsonLight-200-italic": "gibson/Gibson-LightItalic.woff",
  "GibsonLight-200-normal": "gibson/Gibson-Light.woff",
  "GibsonMedium-500-italic": "gibson/Gibson-MediumItalic.woff",
  "GibsonMedium-500-normal": "gibson/Gibson-Medium.woff",
  "GibsonSemiBold-600-italic": "gibson/Gibson-SemiBoldItalic.woff",
  "GibsonSemiBold-600-normal": "gibson/Gibson-SemiBold.woff",
  "GibsonThin-100-italic": "gibson/Gibson-ThinItalic.woff",
  "GibsonThin-100-normal": "gibson/Gibson-Thin.woff",
  "IBMPlexSansCondensed-100-italic":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-100italic.woff",
  "IBMPlexSansCondensed-100-normal":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-100.woff",
  "IBMPlexSansCondensed-200-italic":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-200italic.woff",
  "IBMPlexSansCondensed-200-normal":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-200.woff",
  "IBMPlexSansCondensed-300-italic":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-300italic.woff",
  "IBMPlexSansCondensed-300-normal":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-300.woff",
  "IBMPlexSansCondensed-400-italic":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-italic.woff",
  "IBMPlexSansCondensed-400-normal":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-regular.woff",
  "IBMPlexSansCondensed-500-italic":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-500italic.woff",
  "IBMPlexSansCondensed-500-normal":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-500.woff",
  "IBMPlexSansCondensed-600-italic":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-600italic.woff",
  "IBMPlexSansCondensed-600-normal":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-600.woff",
  "IBMPlexSansCondensed-700-italic":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-700italic.woff",
  "IBMPlexSansCondensed-700-normal":
    "ibm-plex-sans-condensed/ibm-plex-sans-condensed-v14-latin-700.woff",
  "Inter-100-italic": "inter/Inter-ThinItalic.woff2",
  "Inter-100-normal": "inter/Inter-Thin.woff2",
  "Inter-200-italic": "inter/Inter-ExtraLightItalic.woff2",
  "Inter-200-normal": "inter/Inter-ExtraLight.woff2",
  "Inter-300-italic": "inter/Inter-LightItalic.woff2",
  "Inter-300-normal": "inter/Inter-Light.woff2",
  "Inter-400-italic": "inter/Inter-Italic.woff2",
  "Inter-400-normal": "inter/Inter-Regular.woff2",
  "Inter-500-italic": "inter/Inter-MediumItalic.woff2",
  "Inter-500-normal": "inter/Inter-Medium.woff2",
  "Inter-600-italic": "inter/Inter-SemiBoldItalic.woff2",
  "Inter-600-normal": "inter/Inter-SemiBold.woff2",
  "Inter-700-italic": "inter/Inter-BoldItalic.woff2",
  "Inter-700-normal": "inter/Inter-Bold.woff2",
  "Inter-800-italic": "inter/Inter-ExtraBoldItalic.woff2",
  "Inter-800-normal": "inter/Inter-ExtraBold.woff2",
  "Inter-900-italic": "inter/Inter-BlackItalic.woff2",
  "Inter-900-normal": "inter/Inter-Black.woff2",
  "InterDisplay-100-italic": "inter/InterDisplay-ThinItalic.woff2",
  "InterDisplay-100-normal": "inter/InterDisplay-Thin.woff2",
  "InterDisplay-200-italic": "inter/InterDisplay-ExtraLightItalic.woff2",
  "InterDisplay-200-normal": "inter/InterDisplay-ExtraLight.woff2",
  "InterDisplay-300-italic": "inter/InterDisplay-LightItalic.woff2",
  "InterDisplay-300-normal": "inter/InterDisplay-Light.woff2",
  "InterDisplay-400-italic": "inter/InterDisplay-Italic.woff2",
  "InterDisplay-400-normal": "inter/InterDisplay-Regular.woff2",
  "InterDisplay-500-italic": "inter/InterDisplay-MediumItalic.woff2",
  "InterDisplay-500-normal": "inter/InterDisplay-Medium.woff2",
  "InterDisplay-600-italic": "inter/InterDisplay-SemiBoldItalic.woff2",
  "InterDisplay-600-normal": "inter/InterDisplay-SemiBold.woff2",
  "InterDisplay-700-italic": "inter/InterDisplay-BoldItalic.woff2",
  "InterDisplay-700-normal": "inter/InterDisplay-Bold.woff2",
  "InterDisplay-800-italic": "inter/InterDisplay-ExtraBoldItalic.woff2",
  "InterDisplay-800-normal": "inter/InterDisplay-ExtraBold.woff2",
  "InterDisplay-900-italic": "inter/InterDisplay-BlackItalic.woff2",
  "InterDisplay-900-normal": "inter/InterDisplay-Black.woff2",
  "Merriweather-400-italic": "merriweather/merriweather-v30-latin-italic.woff",
  "Merriweather-400-normal": "merriweather/merriweather-v30-latin-regular.woff",
  "Merriweather-700-italic":
    "merriweather/merriweather-v30-latin-700italic.woff",
  "Merriweather-700-normal": "merriweather/merriweather-v30-latin-700.woff",
  "MerriweatherBlack-900-italic":
    "merriweather/merriweather-v30-latin-900italic.woff",
  "MerriweatherBlack-900-normal":
    "merriweather/merriweather-v30-latin-900.woff",
  "MerriweatherLight-300-italic":
    "merriweather/merriweather-v30-latin-300italic.woff",
  "MerriweatherLight-300-normal":
    "merriweather/merriweather-v30-latin-300.woff",
  "National2-400-italic": "national-2/National2-RegularItalic.woff",
  "National2-400-normal": "national-2/National2-Regular.woff",
  "National2-700-italic": "national-2/National2-BoldItalic.woff",
  "National2-700-normal": "national-2/National2-Bold.woff",
  "National2-800-normal": "national-2/National2-Extrabold.woff",
  "National2-900-normal": "national-2/National2-Black.woff",
  "National2Narrow-400-italic": "national-2/National2Narrow-RegularItalic.woff",
  "National2Narrow-400-normal": "national-2/National2Narrow-Regular.woff",
  "NotoSans-100-italic": "noto-sans/noto-sans-v28-latin-100italic.woff",
  "NotoSans-100-normal": "noto-sans/noto-sans-v28-latin-100.woff",
  "NotoSans-200-italic": "noto-sans/noto-sans-v28-latin-200italic.woff",
  "NotoSans-200-normal": "noto-sans/noto-sans-v28-latin-200.woff",
  "NotoSans-300-italic": "noto-sans/noto-sans-v28-latin-300italic.woff",
  "NotoSans-300-normal": "noto-sans/noto-sans-v28-latin-300.woff",
  "NotoSans-400-italic": "noto-sans/noto-sans-v28-latin-italic.woff",
  "NotoSans-400-normal": "noto-sans/noto-sans-v28-latin-regular.woff",
  "NotoSans-500-italic": "noto-sans/noto-sans-v28-latin-500italic.woff",
  "NotoSans-500-normal": "noto-sans/noto-sans-v28-latin-500.woff",
  "NotoSans-600-italic": "noto-sans/noto-sans-v28-latin-600italic.woff",
  "NotoSans-600-normal": "noto-sans/noto-sans-v28-latin-600.woff",
  "NotoSans-700-italic": "noto-sans/noto-sans-v28-latin-700italic.woff",
  "NotoSans-700-normal": "noto-sans/noto-sans-v28-latin-700.woff",
  "NotoSans-800-italic": "noto-sans/noto-sans-v28-latin-800italic.woff",
  "NotoSans-800-normal": "noto-sans/noto-sans-v28-latin-800.woff",
  "NotoSans-900-italic": "noto-sans/noto-sans-v28-latin-900italic.woff",
  "NotoSans-900-normal": "noto-sans/noto-sans-v28-latin-900.woff",
  "Poppins-100-italic": "poppins/Poppins-ThinItalic.woff",
  "Poppins-100-normal": "poppins/Poppins-Thin.woff",
  "Poppins-200-italic": "poppins/Poppins-ExtraLightItalic.woff",
  "Poppins-200-normal": "poppins/Poppins-ExtraLight.woff",
  "Poppins-300-italic": "poppins/Poppins-LightItalic.woff",
  "Poppins-300-normal": "poppins/Poppins-Light.woff",
  "Poppins-400-italic": "poppins/Poppins-Italic.woff",
  "Poppins-400-normal": "poppins/Poppins-Regular.woff",
  "Poppins-500-italic": "poppins/Poppins-MediumItalic.woff",
  "Poppins-500-normal": "poppins/Poppins-Medium.woff",
  "Poppins-600-italic": "poppins/Poppins-SemiBoldItalic.woff",
  "Poppins-600-normal": "poppins/Poppins-SemiBold.woff",
  "Poppins-700-italic": "poppins/Poppins-BoldItalic.woff",
  "Poppins-700-normal": "poppins/Poppins-Bold.woff",
  "Poppins-800-italic": "poppins/Poppins-ExtraBoldItalic.woff",
  "Poppins-800-normal": "poppins/Poppins-ExtraBold.woff",
  "Poppins-900-italic": "poppins/Poppins-BlackItalic.woff",
  "Poppins-900-normal": "poppins/Poppins-Black.woff",
  "PragatiNarrow-400-normal":
    "pragati-narrow/pragati-narrow-v13-latin-regular.woff",
  "PragatiNarrow-700-normal":
    "pragati-narrow/pragati-narrow-v13-latin-700.woff",
  "RedditSans-400-italic": "reddit-sans/RedditSans-Italic.woff",
  "RedditSans-400-normal": "reddit-sans/RedditSans-Regular.woff",
  "RedditSans-700-italic": "reddit-sans/RedditSans-BoldItalic.woff",
  "RedditSans-700-normal": "reddit-sans/RedditSans-Bold.woff",
  "RedditSansBlack-900-italic": "reddit-sans/RedditSans-BlackItalic.woff",
  "RedditSansBlack-900-normal": "reddit-sans/RedditSans-Black.woff",
  "RedditSansExtraBold-800-italic":
    "reddit-sans/RedditSans-ExtraBoldItalic.woff",
  "RedditSansExtraBold-800-normal": "reddit-sans/RedditSans-ExtraBold.woff",
  "RedditSansExtraLight-200-italic":
    "reddit-sans/RedditSans-ExtraLightItalic.woff",
  "RedditSansExtraLight-200-normal": "reddit-sans/RedditSans-ExtraLight.woff",
  "RedditSansLight-300-italic": "reddit-sans/RedditSans-LightItalic.woff",
  "RedditSansLight-300-normal": "reddit-sans/RedditSans-Light.woff",
  "RedditSansMedium-500-italic": "reddit-sans/RedditSans-MediumItalic.woff",
  "RedditSansMedium-500-normal": "reddit-sans/RedditSans-Medium.woff",
  "RedditSansSemiBold-600-italic": "reddit-sans/RedditSans-SemiBoldItalic.woff",
  "RedditSansSemiBold-600-normal": "reddit-sans/RedditSans-SemiBold.woff",
  "Roboto-400-italic": "roboto/Roboto-Italic.woff",
  "Roboto-400-normal": "roboto/Roboto-Regular.woff",
  "Roboto-700-italic": "roboto/Roboto-BoldItalic.woff",
  "Roboto-700-normal": "roboto/Roboto-Bold.woff",
  "RobotoBlack-900-italic": "roboto/Roboto-BlackItalic.woff",
  "RobotoBlack-900-normal": "roboto/Roboto-Black.woff",
  "RobotoCondensed-400-italic":
    "roboto-condensed/roboto-condensed-v25-latin-italic.woff",
  "RobotoCondensed-400-normal":
    "roboto-condensed/roboto-condensed-v25-latin-regular.woff",
  "RobotoCondensed-700-italic":
    "roboto-condensed/roboto-condensed-v25-latin-700italic.woff",
  "RobotoCondensed-700-normal":
    "roboto-condensed/roboto-condensed-v25-latin-700.woff",
  "RobotoCondensedLight-300-italic":
    "roboto-condensed/roboto-condensed-v25-latin-300italic.woff",
  "RobotoCondensedLight-300-normal":
    "roboto-condensed/roboto-condensed-v25-latin-300.woff",
  "RobotoLight-300-italic": "roboto/Roboto-LightItalic.woff",
  "RobotoLight-300-normal": "roboto/Roboto-Light.woff",
  "RobotoMedium-500-italic": "roboto/Roboto-MediumItalic.woff",
  "RobotoMedium-500-normal": "roboto/Roboto-Medium.woff",
  "RobotoMono-100-italic": "roboto-mono/RobotoMono-ThinItalic.woff",
  "RobotoMono-100-normal": "roboto-mono/RobotoMono-Thin.woff",
  "RobotoMono-200-italic": "roboto-mono/RobotoMono-ExtraLightItalic.woff",
  "RobotoMono-200-normal": "roboto-mono/RobotoMono-ExtraLight.woff",
  "RobotoMono-300-italic": "roboto-mono/RobotoMono-LightItalic.woff",
  "RobotoMono-300-normal": "roboto-mono/RobotoMono-Light.woff",
  "RobotoMono-400-italic": "roboto-mono/RobotoMono-Italic.woff",
  "RobotoMono-400-normal": "roboto-mono/RobotoMono-Regular.woff",
  "RobotoMono-500-italic": "roboto-mono/RobotoMono-MediumItalic.woff",
  "RobotoMono-500-normal": "roboto-mono/RobotoMono-Medium.woff",
  "RobotoMono-600-italic": "roboto-mono/RobotoMono-SemiBoldItalic.woff",
  "RobotoMono-600-normal": "roboto-mono/RobotoMono-SemiBold.woff",
  "RobotoMono-700-italic": "roboto-mono/RobotoMono-BoldItalic.woff",
  "RobotoMono-700-normal": "roboto-mono/RobotoMono-Bold.woff",
  "RobotoThin-100-italic": "roboto/Roboto-ThinItalic.woff",
  "RobotoThin-100-normal": "roboto/Roboto-Thin.woff",
  "SourceSans3-200-italic": "source-sans-3/SourceSans3-ExtraLightItalic.woff",
  "SourceSans3-200-normal": "source-sans-3/SourceSans3-ExtraLight.woff",
  "SourceSans3-300-italic": "source-sans-3/SourceSans3-LightItalic.woff",
  "SourceSans3-300-normal": "source-sans-3/SourceSans3-Light.woff",
  "SourceSans3-400-italic": "source-sans-3/SourceSans3-Italic.woff",
  "SourceSans3-400-normal": "source-sans-3/SourceSans3-Regular.woff",
  "SourceSans3-500-italic": "source-sans-3/SourceSans3-MediumItalic.woff",
  "SourceSans3-500-normal": "source-sans-3/SourceSans3-Medium.woff",
  "SourceSans3-600-italic": "source-sans-3/SourceSans3-SemiBoldItalic.woff",
  "SourceSans3-600-normal": "source-sans-3/SourceSans3-SemiBold.woff",
  "SourceSans3-700-italic": "source-sans-3/SourceSans3-BoldItalic.woff",
  "SourceSans3-700-normal": "source-sans-3/SourceSans3-Bold.woff",
  "SourceSans3-800-italic": "source-sans-3/SourceSans3-ExtraBoldItalic.woff",
  "SourceSans3-800-normal": "source-sans-3/SourceSans3-ExtraBold.woff",
  "SourceSans3-900-italic": "source-sans-3/SourceSans3-BlackItalic.woff",
  "SourceSans3-900-normal": "source-sans-3/SourceSans3-Black.woff",
  "SourceSerif4-200-italic":
    "source-serif-4/SourceSerif4-ExtraLightItalic.woff",
  "SourceSerif4-200-normal": "source-serif-4/SourceSerif4-ExtraLight.woff",
  "SourceSerif4-300-italic": "source-serif-4/SourceSerif4-LightItalic.woff",
  "SourceSerif4-300-normal": "source-serif-4/SourceSerif4-Light.woff",
  "SourceSerif4-400-italic": "source-serif-4/SourceSerif4-Italic.woff",
  "SourceSerif4-400-normal": "source-serif-4/SourceSerif4-Regular.woff",
  "SourceSerif4-500-italic": "source-serif-4/SourceSerif4-MediumItalic.woff",
  "SourceSerif4-500-normal": "source-serif-4/SourceSerif4-Medium.woff",
  "SourceSerif4-600-italic": "source-serif-4/SourceSerif4-SemiBoldItalic.woff",
  "SourceSerif4-600-normal": "source-serif-4/SourceSerif4-SemiBold.woff",
  "SourceSerif4-700-italic": "source-serif-4/SourceSerif4-BoldItalic.woff",
  "SourceSerif4-700-normal": "source-serif-4/SourceSerif4-Bold.woff",
  "SourceSerif4-800-italic": "source-serif-4/SourceSerif4-ExtraBoldItalic.woff",
  "SourceSerif4-800-normal": "source-serif-4/SourceSerif4-ExtraBold.woff",
  "SourceSerif4-900-italic": "source-serif-4/SourceSerif4-BlackItalic.woff",
  "SourceSerif4-900-normal": "source-serif-4/SourceSerif4-Black.woff",
} as const;

export type FontIdWoff = keyof typeof FONT_MAP_WOFF;
